### ISSUE TITLE
Webhook Publisher Pod fails to send Webhook

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#226]
## Summary
- GIVEN As an Airy developer having a running Airy cluster with all pods up and running,
- GIVEN I have successfully connected a channel of source type Facebook that can send and receive messages,
- GIVEN I have successfully subscribed `https://my-custom-url` to receive events via the webhook      
- WHEN I receive a new message that is successfully appended to the relevant conversation  
- THEN I don't receive the relevant message payload at `https://my-custom-url` 

## URL:
-

## Steps to reproduce:
- connect a channel of source type Facebook that can successfully send and receive messages,
- subscribe `https://my-custom-url` to receive events via the webhook      
- send a new message to the relevant Facebook page 
- check if the relevant message is successfully appended to the relevant conversation  
- monitor the logs whether the relevant message payload is received at `https://my-custom-url` 
 
## Actual result:
- The relevant message payload is not received at `https://my-custom-url`
- Errors in the Webhook Publisher Pod logs:
```
[2020-11-03 22:20:59,666] [ERROR] [Publisher] {} failed to publish webhook 
org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: CLUSTERDOWN Hash slot not served
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:54) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:52) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceListCommands.convertLettuceAccessException(LettuceListCommands.java:490) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceListCommands.lPush(LettuceListCommands.java:85) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.lPush(DefaultedRedisConnection.java:628) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.lPush(DefaultStringRedisConnection.java:711) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.core.DefaultListOperations.lambda$leftPush$0(DefaultListOperations.java:99) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at org.springframework.data.redis.core.DefaultListOperations.leftPush(DefaultListOperations.java:99) ~[spring-data-redis-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
	at co.airy.core.webhook.publisher.RedisQueue.publishMessage(RedisQueue.java:27) ~[classes!/:?]
	at co.airy.core.webhook.publisher.Publisher.lambda$startStream$3(Publisher.java:55) ~[classes!/:?]
	at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:42) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:43) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:104) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383) ~[kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806) [kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383) [kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475) [kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550) [kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802) [kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697) [kafka-streams-2.5.1.jar!/:?]
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670) [kafka-streams-2.5.1.jar!/:?]
Caused by: io.lettuce.core.RedisCommandExecutionException: CLUSTERDOWN Hash slot not served
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:108) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:680) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:640) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```
## Expected result:
- The message payload is successfully received at `https://my-custom-url`

## Environment: 
Local

## Severity/Priority:
High/High

## Reproducible:
Multiple times

## Browsers:
-

## Platform/OS:
MacBook Pro 16GB RAM

## Date & Time:
03.11.2020 at 22:20 UTC

## Reporter:
steffh

## Notes:

**Comment by pascal-airy** [comment]
There was an issue with Redis which has been resolved.
